name: Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '!master'

jobs:
  windows:
    name: windows-2022
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Nuke Build
        run: ./.nuke/build.cmd --GitHubToken ${{ secrets.GITHUB_TOKEN }}
